#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="doctors")]
public partial class DoctorsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DoctorsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["doctorsConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DoctorsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DoctorsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DoctorsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DoctorsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[Function(Name="dbo.getDrSpecialty")]
	public ISingleResult<getDrSpecialtyResult> getDrSpecialty([Parameter(DbType="Char(4)")] string dr_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dr_id);
		return ((ISingleResult<getDrSpecialtyResult>)(result.ReturnValue));
	}
}

public partial class getDrSpecialtyResult
{
	
	private string _specialty;
	
	public getDrSpecialtyResult()
	{
	}
	
	[Column(Storage="_specialty", DbType="Char(20) NOT NULL", CanBeNull=false)]
	public string specialty
	{
		get
		{
			return this._specialty;
		}
		set
		{
			if ((this._specialty != value))
			{
				this._specialty = value;
			}
		}
	}
}
#pragma warning restore 1591
